"""Shared tile coordinate constants for integration tests.

All coordinates are verified against the actual mbtiles data served by
the tileserver-gl instance under test.
"""

import json
from pathlib import Path

# ---------------------------------------------------------------------------
# Deterministic tile samples (generated by generate_tile_samples.py)
# Used by stress, sustained load, and performance tests.
# ---------------------------------------------------------------------------

_SAMPLES_PATH = Path(__file__).parent / "tile_samples.json"
_SAMPLES = json.loads(_SAMPLES_PATH.read_text())


def tiles_for(source: str, max_zoom: int | None = None) -> list[dict]:
    """Return tile samples for a source, optionally capped at max_zoom."""
    src = _SAMPLES["sources"][source]
    tiles = src["tiles"]
    if max_zoom is not None:
        tiles = [t for t in tiles if t["z"] <= max_zoom]
    return tiles


# ---------------------------------------------------------------------------
# Style and source names
# ---------------------------------------------------------------------------

STYLE = "rwgpscycle"
STYLE_FLAT = STYLE + "-flat"
RENDERED_STYLES = [STYLE, STYLE_FLAT]

DATA_RWGPS = "rwgps"
DATA_ELEVATION = "elevation"
DATA_SNOW = "snow_depth"

# ---------------------------------------------------------------------------
# Rendered tile coordinates (rwgpscycle style)
# ---------------------------------------------------------------------------

# Portland urban area — dense vector data, good for rendered tile checks
URBAN = {"z": 10, "x": 163, "y": 366}

# Mt Hood — strong hillshade relief
HILLSHADE = {"z": 10, "x": 165, "y": 366}

# Kansas — flat terrain, minimal hillshade
FLAT = {"z": 10, "x": 236, "y": 391}

# ---------------------------------------------------------------------------
# Vector tile coordinates (rwgps / output.mbtiles)
# ---------------------------------------------------------------------------

# Portland — same location as URBAN, named for vector test context
VECTOR_PORTLAND = URBAN

# Mid-Atlantic Ocean — confirmed absent
VECTOR_NO_DATA = {"z": 10, "x": 398, "y": 618}

# ---------------------------------------------------------------------------
# Elevation tile coordinates (elevation.mbtiles, z0-z12, Terrain-RGB PNG)
# ---------------------------------------------------------------------------

# Mt Hood — same location as HILLSHADE, confirmed present
ELEV_WITH_DATA = HILLSHADE

# Pacific Ocean — confirmed absent in CONUS elevation extract
ELEV_NO_DATA = {"z": 10, "x": 85, "y": 422}

# ---------------------------------------------------------------------------
# Snow depth tile coordinates (snow_depth.mbtiles, z1-z10, PNG raster)
# ---------------------------------------------------------------------------

# Portland area — confirmed present
SNOW_WITH_DATA = {"z": 8, "x": 40, "y": 91}

# Pacific Ocean — confirmed absent
SNOW_NO_DATA = {"z": 8, "x": 10, "y": 155}

# ---------------------------------------------------------------------------
# Error case coordinates (shared across tests)
# ---------------------------------------------------------------------------

# Exceeds 2^z tile range — triggers 400
OUT_OF_RANGE = {"z": 10, "x": 99999, "y": 99999}

# ---------------------------------------------------------------------------
# URL builders
# ---------------------------------------------------------------------------


def rendered_url(style: str, tile: dict, fmt: str = "png", scale: str = "") -> str:
    """Build a rendered tile URL. scale="" for 1x, "@2x" for retina."""
    return f"/styles/{style}/{tile['z']}/{tile['x']}/{tile['y']}{scale}.{fmt}"


def data_url(source: str, tile: dict, fmt: str) -> str:
    """Build a data tile URL."""
    return f"/data/{source}/{tile['z']}/{tile['x']}/{tile['y']}.{fmt}"
