---
apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: regcred
  containers:
  - name: tileserver-integration-tests
    image: registry.ridewithgps.com/rwgps/tileserver-integration-tests:1.0.0
    command:
    - 'sleep'
    args:
    - 'infinity'
